apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-lccf
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-cqnj-tenant/status-quarkus-io/statusquarkusio-lccf@sha256:e2ecd44530ccb17b616ef2564469995df184a2264e84ccafcbbbedba36a49751
        name: my-java-quarkus
        resources: {}
status: {}
