apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-lccf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-lccf
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-lccf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-lccf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-lccf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-cqnj-tenant/status-quarkus-io/statusquarkusio-lccf@sha256:e2ecd44530ccb17b616ef2564469995df184a2264e84ccafcbbbedba36a49751
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
